### PR TITLE
Interface exp

### PR DESCRIPTION
**Pull request by pshriwise**
Further interface expansion. Adds:
- load_file
- get_adjacencies
- type_from_handle
- get_child_meshsets
- add_child_meshset
- get_root_set --> @vijaysm I'd like you to take a look at the implementation for that one
- get_coords
- get_entities_by_type
- get_entities_by_type_and_tag --> this one required some changes to the current pymoab Tag class and the addition of a TagArray class

These are all being added in the anticipation of replacing iMesh in PyNE

### CODE REVIEW

**Comment by scopatz** [comment]
Hey @Pshriwise what version of MOAB are you using? I seem to be on v4.8.1 and I can't even get master to compile locally.

**Comment by vijaysm** [comment]
MOAB's latest release is 4.9.0 and in couple of days, that should become
4.9.1. So if possible, we should keep this synced with MOAB builds.

I can look at adding one or two nightly buildbot tests for PyMOAB.
@Pshriwise would this help ?

**Comment by pshriwise** [comment]
@scopatz what error are you getting? I just built with 4.8.1. No problems. Did you link the TagInfo header into the include/moab/ directory? This is still an issue (#1) we have not settled yet.

@vijaysm that would be extremely helpful!

**Comment by scopatz** [comment]
Wait, so where does the TagInfo header actually live?

**Comment by pshriwise** [comment]
[here](https://bitbucket.org/fathomteam/moab/src/a1bcb7e65e109a14087c1106b316c03d656c801d/src/TagInfo.hpp?at=master&fileviewer=file-view-default) I believe

**Comment by vijaysm** [comment]
Patrick, the problem with installing TagInfo is that it forward
declares private objects such as SequenceManager (which
doesn't/shouldn't need to be installed), and also exposes library-wise
internal calls (that access SequenceManager directly). These routines
can really destroy performance if available as a public API for users
and I think Tim made the design choice to not install TagInfo and
SequenceManager. I'm unsure how this was handled previously in PyTAPS
to see if that can help.

**Comment by pshriwise** [comment]
I see. That's a very good reason not to install the TagInfo header. The current solution is one that @scopatz and I came up with on the fly. I should be open to other options as well. One suggestion from @gonuke was to incorporate pymoab into moab itself to give it access to these headers. This would make testing straight forward as well. Thoughts? 

I'll take a look in pytaps today to see how this issue is handled there.

**Comment by scopatz** [comment]
Hi all, I think we need to come up with a way to solve this because otherwise we can't have CI, we can't test, etc.  Not actually having to do any of the work @gonuke's suggestion is attractive.

**Comment by vijaysm** [comment]
I do not have a problem with integrating PyMOAB directly into MOAB sources
as long as there is a nice separation of concerns. I just don't want to
make the moab repo polluted for those users who do not need python
interfaces. If there are ideas on how to do this, will be very interested.

@pshriwise @scopatz we could create a fork of MOAB and use subtree
semantics to bring the repo along with all commit messages. But let's
discuss layout and design first.

**Comment by scopatz** [comment]
I don't think I am qualified to make a judgement yet.  I would think it would be relatively easy to add an `--enable-python` flag or some such to the build system, such that the binding were built if Python were detected and/or if it was requested explicitly.

**Comment by scopatz** [comment]
I have some code to help out with this with CMake scattered throughout PyNE et al.

**Comment by pshriwise** [comment]
Hey all! This one's been open for a while now. 

Vijay and I have talked offline and we agreed that moving pymoab into MOAB is a good plan for the build process so long as MOAB is okay with taking on the necessary dependencies that come with the python interface which became a part of the discussion here. 

But as far as the additions to this PR, how are we looking?

**Comment by vijaysm** [comment]
Patrick, the PR looks good to me. I think the tests are a good start and we can certainly add more later.

Regarding the merge to MOAB, let me play with some sample use cases. For PyMOAB, other than MOAB, numpy and Cython, are there any other dependencies ? I'm thinking of just adding a target to autoconf configure to say --with-python and it will configure PyMOAB with the shared MOAB installation. Perhaps that may not be optimal and I'm open to suggestions here.

**Comment by pshriwise** [comment]
ping @scopatz

**Comment by pshriwise** [comment]
Vijay, there are some other equally common python packages needed to actually build and install pymoab such as setuptools, libcpp, sys, and os. When adding this to MOAB we should make sure that ensuring these packages are available and installing them if they aren't as part of the build.

**Comment by vijaysm** [comment]
Sure we can do a configuration check if these packages are available in the standard python path. But installing them ?! I don't want to do that. There are many modes for this and I'd rather not do something here automatically, without knowing how the user has things setup. For example, with sudo, or virtualenv or brew/port or something else ..

Unless you are talking about installing something in a sandbox folder, within the build directory ? Not sure how to go about that either..

**Comment by pshriwise** [comment]
That is so true. I misspoke. A configuration check would be best. Outside of that we'll just need to make it clear that the python interface will require a few additional dependencies and report missing ones if they aren't found during the configuration step.

**Comment by pshriwise** [comment]
Any further comments on this @scopatz @vijaysm? 

Going to merge in the interest of progress if not...

**Comment by pshriwise** [comment]
closing now that this project has become part of MOAB proper http://sigma.mcs.anl.gov/moab-library/

**Comment by scopatz** [comment]
Sounds good! Should we add something to this repo's readme about how development has moved?

**Pull request closed without merging**
