### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by pshriwise**
Updated build to search for an environment variable. 

Added a README to make requirements and build instructions more clear.

### CODE REVIEW

**Comment by vijaysm** [comment]
Hi Patrick, we should catch up some time next week or the week after on making more progress to PyMOAB. Do you think there will be value in exposing CGM and MeshKit via similar Pythonic interfaces ? It certainly would fit great under my PySIGMA vision.

**Comment by scopatz** [comment]
There should probably be a sensible default for `MOAB_PATH` and a command line option, too. But this is a big improvement over the hard coded path that is there now, so I'll go ahead and merge it. Thanks @Pshriwise!

**Comment by pshriwise** [comment]
@scopatz I can definitely work on adding a command line option. Definitely a reasonable expectation. Do you have any suggestions for a default value? There is a aptitude package for MOAB now I think, but most installations are probably still user

@vijaysm I think this would be a great thing to do for MeshKit! A lot of the abstract ideas for connecting the geometry to the mesh and meshops might be easier to understand/use in a pythonic format. 

I'm not sure about CGM, even the GeometryQuery and GeometryModify tools in CGM can be difficult to work in. I have a feeling that it would be difficult to implement something useful that wouldn't cause that whole system to seem even more opaque when things go wrong in manipulating the geometry.

Also, I haven't heard of PySIGMA. Is it another interface to these tools? I'd love to have a look. If it doesn't already exist, PyMOAB could become a submodule of that?

**Comment by scopatz** [comment]
Hmm yeah, I would say that maybe `$USER/.local` would be a reasonable default if it is expected to be in user space or wherever the debian package installs it.

**Pull request merged**
